version: 2
jobs: 
  tests:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/setup.sh

  release:
    machine: true
    steps:
      - checkout
      - run: ./docker-build.sh
      - run: ./.circleci/release.sh

workflows:
  version: 2
  build:
    jobs:
      - tests
      - release:
          requires:
            - tests
          filters:
            branches:
              only:
                - feature/docker
            tags:
              only: /^v.*/
